<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<script type="text/javascript" src="resources/customer/js/html2canvas.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<style>
    .scale-down-center {
        -webkit-animation: scale-down-center 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
                animation: scale-down-center 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2019-1-23 14:12:58
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation scale-down-center
    * ----------------------------------------
    */
    @-webkit-keyframes scale-down-center {
    0% {
        opacity: 0;
        -webkit-transform: scale(1.5) translateY(-30px);
                transform: scale(1.5) translateY(-30px);
    }
    100% {
        opacity: 1;
        -webkit-transform: scale(1) translateY(0);
                transform: scale(1) translateY(0);
    }
    }
    @keyframes scale-down-center {
    0% {
        opacity: 0;
        -webkit-transform: scale(1.5) translateY(-30px);
                transform: scale(1.5) translateY(-30px);
    }
    100% {
        opacity: 1;
        -webkit-transform: scale(1) translateY(0);
                transform: scale(1) translateY(0);
    }
    }
	

	.canvasPlace{
		position: relative;
		width: 600px;
		height: 520px;
	}
	.placeImg{
		position: absolute;
		width: 600px;
		z-index: 0;
	}
	.canvas{
		position: absolute;
		left: 43px;
		top: 43px;
		outline: 1px solid black;
		z-index: 1;
	}
	.toppings{
		position: absolute;
		width: 420px;
		height: 420px;
		left: 43px;
		top: 43px;
		outline: 1px solid black;
		z-index: 1;
	}
</style>
</head>
<body>
	<br><br><br>
	<table>
		<tfoot>
			<tr>
				<td>
					<div class="canvasPlace">
						<img class="placeImg" src="resources/customer/images/order/pizza_place.png">
						<canvas id="pizzaCanvas" class="canvas" width="420px" height="420px"></canvas>
						<div id="toppings" class="toppings"></div>
					</div>
				</td>
				<td>
					<div style="border: 1px solid black; width: 400px; height: 520px;"></div>
				</td>
			</tr>
		</tfoot>
		
	</table>
	
	
	<button onclick="dough();">도우</button>
	<script>
		$(function(){
			$("#pizzaCanvas").hide();
		});
		function dough(){
			var canvas = document.getElementById('pizzaCanvas').getContext('2d');
			
			var img1 = new Image();
			$(img1).attr("src", "resources/customer/images/order/dough.png");
			$(img1).addClass("scale-down-center");
			$(img1).css({"position":"absolute", "z-index":"2", "width":"420px", "height":"420px"});
			canvas.drawImage(img1, 0, 0, 420, 420);
			
			$("#toppings").append(img1);
		}
	</script>
</body>
</html>