<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<style>
    .scale-down-center {
        -webkit-animation: scale-down-center 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
                animation: scale-down-center 0.7s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2019-1-23 14:12:58
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation scale-down-center
    * ----------------------------------------
    */
    @-webkit-keyframes scale-down-center {
    0% {
        opacity: 0;
        -webkit-transform: scale(1.5) translateY(-30px);
                transform: scale(1.5) translateY(-30px);
    }
    100% {
        opacity: 1;
        -webkit-transform: scale(1) translateY(0);
                transform: scale(1) translateY(0);
    }
    }
    @keyframes scale-down-center {
    0% {
        opacity: 0;
        -webkit-transform: scale(1.5) translateY(-30px);
                transform: scale(1.5) translateY(-30px);
    }
    100% {
        opacity: 1;
        -webkit-transform: scale(1) translateY(0);
                transform: scale(1) translateY(0);
    }
    }
	
	
	.scale-up-center {
		-webkit-animation: scale-up-center 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
		        animation: scale-up-center 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2019-1-25 12:35:32
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation scale-up-center
	 * ----------------------------------------
	 */
	@-webkit-keyframes scale-up-center {
	  0% {
	  	opacity: 0;
	    -webkit-transform: scale(0.5) translateY(-30px);
	            transform: scale(0.5) translateY(-30px);
	  }
	  100% {
	  	opacity: 1;
	    -webkit-transform: scale(1) translateY(0);
	            transform: scale(1) translateY(0);
	  }
	}
	@keyframes scale-up-center {
	  0% {
	  	opacity: 0;
	    -webkit-transform: scale(0.5) translateY(-30px);
	            transform: scale(0.5) translateY(-30px);
	  }
	  100% {
	  	opacity: 1;
	    -webkit-transform: scale(1) translateY(0);
	            transform: scale(1) translateY(0);
	  }
	}


	.canvasPlace{
		position: relative;
		width: 600px;
		height: 520px;
	}
	.placeImg{
		position: absolute;
		width: 600px;
		z-index: 0;
	}
	.toppings{
		position: absolute;
		width: 420px;
		height: 420px;
		left: 43px;
		top: 43px;
		outline: 1px solid black;
		z-index: 1;
	}
</style>
</head>
<body>
	<br><br><br>
	
	
	<table>
		<tbody>
			<tr>
				<td>
					<div class="canvasPlace">
						<img class="placeImg" src="resources/customer/images/order/pizza_place.png">
						<div id="toppings" class="toppings"></div>
					</div>
				</td>
				<td>
					<div style="border: 1px solid black; width: 400px; height: 520px;"></div>
				</td>
			</tr>
		</tbody>
	</table>
	
	
	<button onclick="dough();">도우</button>
	<button onclick="sauce();">소스</button>
	<script>
		function dough(){
			var $dough = $("<img>");
			$dough.attr("src", "resources/customer/images/order/dough.png");
			$dough.addClass("scale-down-center");
			$dough.css({"position":"absolute", "z-index":"2", "width":"420px", "height":"420px"});
			
			$("#toppings").append($dough);
		}
		function sauce(){
			var $sauce = $("<img>");
			$sauce.attr("src", "resources/customer/images/order/tomato_sauce.png");
			$sauce.addClass("scale-up-center");
			$sauce.css({"position":"absolute", "z-index":"3", "width":"420px", "height":"420px"});
			
			$("#toppings").append($sauce);
		}
	</script>
</body>
</html>